/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SevasRouteImport } from './routes/sevas'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountSubscriptionsRouteImport } from './routes/account.subscriptions'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPoojasRouteImport } from './routes/admin.poojas'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookingSuccessBookingIdRouteImport } from './routes/booking-success.$bookingId'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsSlugRouteImport } from './routes/campaigns.$slug'
import { Route as DonationSuccessDonationIdRouteImport } from './routes/donation-success.$donationId'
import { Route as MyBookingsIndexRouteImport } from './routes/my-bookings.index'
import { Route as MyBookingsIdRouteImport } from './routes/my-bookings.$id'
import { Route as MyOrdersIndexRouteImport } from './routes/my-orders.index'
import { Route as MyOrdersIdRouteImport } from './routes/my-orders.$id'
import { Route as OrderSuccessOrderIdRouteImport } from './routes/order-success.$orderId'
import { Route as PaymentBookingIdRouteImport } from './routes/payment.$bookingId'
import { Route as PoojasIndexRouteImport } from './routes/poojas.index'
import { Route as PoojasSlugRouteImport } from './routes/poojas.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as PaymentDonationDonationIdRouteImport } from './routes/payment.donation.$donationId'
import { Route as PaymentOrderOrderIdRouteImport } from './routes/payment.order.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SevasRoute = SevasRouteImport.update({
  id: '/sevas',
  path: '/sevas',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSubscriptionsRoute = AccountSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoojasRoute = AdminPoojasRouteImport.update({
  id: '/poojas',
  path: '/poojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessBookingIdRoute = BookingSuccessBookingIdRouteImport.update({
  id: '/booking-success/$bookingId',
  path: '/booking-success/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsSlugRoute = CampaignsSlugRouteImport.update({
  id: '/campaigns/$slug',
  path: '/campaigns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationSuccessDonationIdRoute =
  DonationSuccessDonationIdRouteImport.update({
    id: '/donation-success/$donationId',
    path: '/donation-success/$donationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyBookingsIndexRoute = MyBookingsIndexRouteImport.update({
  id: '/my-bookings/',
  path: '/my-bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsIdRoute = MyBookingsIdRouteImport.update({
  id: '/my-bookings/$id',
  path: '/my-bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersIndexRoute = MyOrdersIndexRouteImport.update({
  id: '/my-orders/',
  path: '/my-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersIdRoute = MyOrdersIdRouteImport.update({
  id: '/my-orders/$id',
  path: '/my-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessOrderIdRoute = OrderSuccessOrderIdRouteImport.update({
  id: '/order-success/$orderId',
  path: '/order-success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentBookingIdRoute = PaymentBookingIdRouteImport.update({
  id: '/payment/$bookingId',
  path: '/payment/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojasIndexRoute = PoojasIndexRouteImport.update({
  id: '/poojas/',
  path: '/poojas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojasSlugRoute = PoojasSlugRouteImport.update({
  id: '/poojas/$slug',
  path: '/poojas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDonationDonationIdRoute =
  PaymentDonationDonationIdRouteImport.update({
    id: '/payment/donation/$donationId',
    path: '/payment/donation/$donationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentOrderOrderIdRoute = PaymentOrderOrderIdRouteImport.update({
  id: '/payment/order/$orderId',
  path: '/payment/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sevas': typeof SevasRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/poojas': typeof AdminPoojasRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking-success/$bookingId': typeof BookingSuccessBookingIdRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/donation-success/$donationId': typeof DonationSuccessDonationIdRoute
  '/my-bookings/$id': typeof MyBookingsIdRoute
  '/my-orders/$id': typeof MyOrdersIdRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/my-bookings/': typeof MyBookingsIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/poojas/': typeof PoojasIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/payment/donation/$donationId': typeof PaymentDonationDonationIdRoute
  '/payment/order/$orderId': typeof PaymentOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sevas': typeof SevasRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/poojas': typeof AdminPoojasRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking-success/$bookingId': typeof BookingSuccessBookingIdRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/donation-success/$donationId': typeof DonationSuccessDonationIdRoute
  '/my-bookings/$id': typeof MyBookingsIdRoute
  '/my-orders/$id': typeof MyOrdersIdRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/my-bookings': typeof MyBookingsIndexRoute
  '/my-orders': typeof MyOrdersIndexRoute
  '/poojas': typeof PoojasIndexRoute
  '/shop': typeof ShopIndexRoute
  '/payment/donation/$donationId': typeof PaymentDonationDonationIdRoute
  '/payment/order/$orderId': typeof PaymentOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/account-deletion': typeof AccountDeletionRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sevas': typeof SevasRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/poojas': typeof AdminPoojasRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking-success/$bookingId': typeof BookingSuccessBookingIdRoute
  '/campaigns/$slug': typeof CampaignsSlugRoute
  '/donation-success/$donationId': typeof DonationSuccessDonationIdRoute
  '/my-bookings/$id': typeof MyBookingsIdRoute
  '/my-orders/$id': typeof MyOrdersIdRoute
  '/order-success/$orderId': typeof OrderSuccessOrderIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/my-bookings/': typeof MyBookingsIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/poojas/': typeof PoojasIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/payment/donation/$donationId': typeof PaymentDonationDonationIdRoute
  '/payment/order/$orderId': typeof PaymentOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/account-deletion'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/sevas'
    | '/signup'
    | '/terms'
    | '/account/subscriptions'
    | '/admin/bookings'
    | '/admin/campaigns'
    | '/admin/donations'
    | '/admin/orders'
    | '/admin/poojas'
    | '/admin/products'
    | '/admin/users'
    | '/book/$slug'
    | '/booking-success/$bookingId'
    | '/campaigns/$slug'
    | '/donation-success/$donationId'
    | '/my-bookings/$id'
    | '/my-orders/$id'
    | '/order-success/$orderId'
    | '/payment/$bookingId'
    | '/poojas/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/campaigns/'
    | '/my-bookings/'
    | '/my-orders/'
    | '/poojas/'
    | '/shop/'
    | '/payment/donation/$donationId'
    | '/payment/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/account-deletion'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/sevas'
    | '/signup'
    | '/terms'
    | '/account/subscriptions'
    | '/admin/bookings'
    | '/admin/campaigns'
    | '/admin/donations'
    | '/admin/orders'
    | '/admin/poojas'
    | '/admin/products'
    | '/admin/users'
    | '/book/$slug'
    | '/booking-success/$bookingId'
    | '/campaigns/$slug'
    | '/donation-success/$donationId'
    | '/my-bookings/$id'
    | '/my-orders/$id'
    | '/order-success/$orderId'
    | '/payment/$bookingId'
    | '/poojas/$slug'
    | '/shop/$slug'
    | '/admin'
    | '/campaigns'
    | '/my-bookings'
    | '/my-orders'
    | '/poojas'
    | '/shop'
    | '/payment/donation/$donationId'
    | '/payment/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/account-deletion'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/sevas'
    | '/signup'
    | '/terms'
    | '/account/subscriptions'
    | '/admin/bookings'
    | '/admin/campaigns'
    | '/admin/donations'
    | '/admin/orders'
    | '/admin/poojas'
    | '/admin/products'
    | '/admin/users'
    | '/book/$slug'
    | '/booking-success/$bookingId'
    | '/campaigns/$slug'
    | '/donation-success/$donationId'
    | '/my-bookings/$id'
    | '/my-orders/$id'
    | '/order-success/$orderId'
    | '/payment/$bookingId'
    | '/poojas/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/campaigns/'
    | '/my-bookings/'
    | '/my-orders/'
    | '/poojas/'
    | '/shop/'
    | '/payment/donation/$donationId'
    | '/payment/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AccountDeletionRoute: typeof AccountDeletionRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SevasRoute: typeof SevasRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingSuccessBookingIdRoute: typeof BookingSuccessBookingIdRoute
  CampaignsSlugRoute: typeof CampaignsSlugRoute
  DonationSuccessDonationIdRoute: typeof DonationSuccessDonationIdRoute
  MyBookingsIdRoute: typeof MyBookingsIdRoute
  MyOrdersIdRoute: typeof MyOrdersIdRoute
  OrderSuccessOrderIdRoute: typeof OrderSuccessOrderIdRoute
  PaymentBookingIdRoute: typeof PaymentBookingIdRoute
  PoojasSlugRoute: typeof PoojasSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  MyBookingsIndexRoute: typeof MyBookingsIndexRoute
  MyOrdersIndexRoute: typeof MyOrdersIndexRoute
  PoojasIndexRoute: typeof PoojasIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  PaymentDonationDonationIdRoute: typeof PaymentDonationDonationIdRoute
  PaymentOrderOrderIdRoute: typeof PaymentOrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sevas': {
      id: '/sevas'
      path: '/sevas'
      fullPath: '/sevas'
      preLoaderRoute: typeof SevasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/subscriptions': {
      id: '/account/subscriptions'
      path: '/subscriptions'
      fullPath: '/account/subscriptions'
      preLoaderRoute: typeof AccountSubscriptionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/poojas': {
      id: '/admin/poojas'
      path: '/poojas'
      fullPath: '/admin/poojas'
      preLoaderRoute: typeof AdminPoojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success/$bookingId': {
      id: '/booking-success/$bookingId'
      path: '/booking-success/$bookingId'
      fullPath: '/booking-success/$bookingId'
      preLoaderRoute: typeof BookingSuccessBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$slug': {
      id: '/campaigns/$slug'
      path: '/campaigns/$slug'
      fullPath: '/campaigns/$slug'
      preLoaderRoute: typeof CampaignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation-success/$donationId': {
      id: '/donation-success/$donationId'
      path: '/donation-success/$donationId'
      fullPath: '/donation-success/$donationId'
      preLoaderRoute: typeof DonationSuccessDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings/': {
      id: '/my-bookings/'
      path: '/my-bookings'
      fullPath: '/my-bookings/'
      preLoaderRoute: typeof MyBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings/$id': {
      id: '/my-bookings/$id'
      path: '/my-bookings/$id'
      fullPath: '/my-bookings/$id'
      preLoaderRoute: typeof MyBookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders/': {
      id: '/my-orders/'
      path: '/my-orders'
      fullPath: '/my-orders/'
      preLoaderRoute: typeof MyOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders/$id': {
      id: '/my-orders/$id'
      path: '/my-orders/$id'
      fullPath: '/my-orders/$id'
      preLoaderRoute: typeof MyOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success/$orderId': {
      id: '/order-success/$orderId'
      path: '/order-success/$orderId'
      fullPath: '/order-success/$orderId'
      preLoaderRoute: typeof OrderSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$bookingId': {
      id: '/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof PaymentBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poojas/': {
      id: '/poojas/'
      path: '/poojas'
      fullPath: '/poojas/'
      preLoaderRoute: typeof PoojasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poojas/$slug': {
      id: '/poojas/$slug'
      path: '/poojas/$slug'
      fullPath: '/poojas/$slug'
      preLoaderRoute: typeof PoojasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/donation/$donationId': {
      id: '/payment/donation/$donationId'
      path: '/payment/donation/$donationId'
      fullPath: '/payment/donation/$donationId'
      preLoaderRoute: typeof PaymentDonationDonationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/order/$orderId': {
      id: '/payment/order/$orderId'
      path: '/payment/order/$orderId'
      fullPath: '/payment/order/$orderId'
      preLoaderRoute: typeof PaymentOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountSubscriptionsRoute: typeof AccountSubscriptionsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountSubscriptionsRoute: AccountSubscriptionsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPoojasRoute: typeof AdminPoojasRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPoojasRoute: AdminPoojasRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AccountDeletionRoute: AccountDeletionRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SevasRoute: SevasRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BookSlugRoute: BookSlugRoute,
  BookingSuccessBookingIdRoute: BookingSuccessBookingIdRoute,
  CampaignsSlugRoute: CampaignsSlugRoute,
  DonationSuccessDonationIdRoute: DonationSuccessDonationIdRoute,
  MyBookingsIdRoute: MyBookingsIdRoute,
  MyOrdersIdRoute: MyOrdersIdRoute,
  OrderSuccessOrderIdRoute: OrderSuccessOrderIdRoute,
  PaymentBookingIdRoute: PaymentBookingIdRoute,
  PoojasSlugRoute: PoojasSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  MyBookingsIndexRoute: MyBookingsIndexRoute,
  MyOrdersIndexRoute: MyOrdersIndexRoute,
  PoojasIndexRoute: PoojasIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  PaymentDonationDonationIdRoute: PaymentDonationDonationIdRoute,
  PaymentOrderOrderIdRoute: PaymentOrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
